use crate::config::{PreludeTier, StackSize};

pub struct Demo {
    pub title: &'static str,
    pub description: &'static str,
    pub source: &'static str,
    pub prelude: PreludeTier,
    pub stack: StackSize,
    pub category: &'static str,
}

pub const DEMOS: &[Demo] = &[
    Demo {
        title: "Tail-Call Optimization",
        description: "Deep recursion without stack overflow via TCO",
        source: include_str!("../../tml24c/demos/tco.l24"),
        prelude: PreludeTier::Minimal,
        stack: StackSize::EightKb,
        category: "Language",
    },
    Demo {
        title: "Macros",
        description: "let, cond, and, or — core macro system",
        source: include_str!("../../tml24c/demos/macros.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Quasiquote",
        description: "Template expansion with unquote and splicing",
        source: include_str!("../../tml24c/demos/quasiquote.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Variadic Functions",
        description: "Rest parameters: (lambda args ...) and (lambda (a . rest) ...)",
        source: include_str!("../../tml24c/demos/variadic.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Strings",
        description: "String type: length, append, ref, conversion",
        source: include_str!("../../tml24c/demos/strings.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Mutation",
        description: "set!, closures as state, memoization patterns",
        source: include_str!("../../tml24c/demos/mutation.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Metaprogramming",
        description: "macroexpand, gensym, eval, symbol/string conversion",
        source: include_str!("../../tml24c/demos/metaprogramming.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Multi-line Input",
        description: "Balanced-paren tracking across newlines",
        source: include_str!("../../tml24c/demos/multiline.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Threading Macros",
        description: "-> (thread-first) and ->> (thread-last) pipelines",
        source: include_str!("../../tml24c/demos/threading.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Lazy Sequences",
        description: "Infinite streams, lazy-map, lazy-filter, fibonacci",
        source: include_str!("../../tml24c/demos/lazy.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::EightKb,
        category: "Language",
    },
    Demo {
        title: "Anaphoric Macros",
        description: "Unhygienic macros: aif, awhen, aand with implicit 'it'",
        source: include_str!("../../tml24c/demos/anaphora.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Utility Functions",
        description: "partial, juxt, doseq, dotimes — Clojure-inspired",
        source: include_str!("../../tml24c/demos/utilities.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::ThreeKb,
        category: "Language",
    },
    Demo {
        title: "Bottles of Beer",
        description: "99 Bottles via macro + TCO (5 verses)",
        source: include_str!("../../tml24c/demos/bottles.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Application",
    },
    Demo {
        title: "Bottles (Trampoline)",
        description: "Full 99 Bottles via mutual-recursion trampoline",
        source: include_str!("../../tml24c/demos/bottles2.l24"),
        prelude: PreludeTier::Full,
        stack: StackSize::EightKb,
        category: "Application",
    },
    Demo {
        title: "Bottles (Functional)",
        description: "99 Bottles via map/for-each — functional style",
        source: include_str!("../../tml24c/demos/bottles4.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Application",
    },
    Demo {
        title: "Blink LED",
        description: "Toggle LED D2 via memory-mapped I/O",
        source: include_str!("../../tml24c/demos/blink.l24"),
        prelude: PreludeTier::Standard,
        stack: StackSize::ThreeKb,
        category: "Hardware",
    },
];
